spring:
  thymeleaf:
    encoding: UTF-8
  application:
    name: detoxmate
  profiles:
    default: local
    group:
      dev: dev
      local: local
      prod: prod

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: /openapi3.yaml

app:
  storage:
    image-read-base-url: https://detoxmate-media-dev.s3.ap-northeast-2.amazonaws.com
    s3:
      region: ap-northeast-2
      bucket-name: detoxmate-media-dev
      presigned-url-expires-in: 600
