spring:
  thymeleaf:
    encoding: UTF-8
  application:
    name: detoxmate
  profiles:
    default: local
    group:
      dev: dev
      local: local
      prod: prod

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: /openapi3.yaml

app:
  storage:
    image-read-base-url: ${STORAGE_IMAGE_READ_BASE_URL}
    s3:
      region: ${AWS_REGION:ap-northeast-2}
      bucket-name: ${S3_BUCKET_NAME}
      presigned-url-expires-in: ${S3_PRESIGNED_URL_EXPIRES_IN:600}
