= Detoxmate API Docs
:toc: left
:toclevels: 2

== Auth API

=== Kakao Social Login

operation::auth/social/kakao[snippets='http-request,request-fields,http-response,response-fields']
operation::auth/social/kakao-invalid-request[snippets='http-request,request-fields,http-response,response-fields']

=== Refresh Access Token

operation::auth/refresh[snippets='http-request,request-fields,http-response,response-fields']
operation::auth/refresh-invalid-request[snippets='http-request,request-fields,http-response,response-fields']

=== Logout

operation::auth/logout[snippets='http-request,request-fields,http-response']
operation::auth/logout-invalid-request[snippets='http-request,request-fields,http-response,response-fields']

== User API

=== Get My Profile

operation::users/me-get[snippets='http-request,request-headers,http-response,response-fields']
operation::users/me-get-unauthorized[snippets='http-request,request-headers,http-response,response-fields']

=== Withdraw My Account

operation::users/me-delete[snippets='http-request,request-headers,http-response']
operation::users/me-delete-unauthorized[snippets='http-request,request-headers,http-response,response-fields']

== Group API

=== Create Group

operation::groups/create[snippets='http-request,request-fields,http-response,response-fields']

=== Join Group

operation::groups/join[snippets='http-request,request-fields,http-response,response-fields']

=== Get My Groups

operation::me/groups-get[snippets='http-request,http-response,response-fields']

=== Get Group Detail

operation::groups/get-by-id[snippets='http-request,path-parameters,http-response,response-fields']

== Group Challenge API

=== Get My Group Challenges

operation::me/group-challenges-get[snippets='http-request,query-parameters,http-response,response-fields']

=== Get Group Challenge Detail

operation::group-challenges/get-by-id[snippets='http-request,path-parameters,http-response,response-fields']

  == Feed API

  === Get Home Feed

  operation::group-challenges/home-feed-get[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

  === Get Feed Detail

  operation::group-challenges/feed-detail-get[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

  == Reaction API

  === Create Reaction

  operation::group-challenges/reaction-create[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']

  === Delete Reaction

  operation::group-challenges/reaction-delete[snippets='http-request,request-headers,path-parameters,http-response']

  == Comment API

  === List Comments

  operation::group-challenges/comments-list-get[snippets='http-request,request-headers,path-parameters,query-parameters,http-response,response-fields']

  === Create Comment

  operation::group-challenges/comment-create[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']

  == Poke API

  === Poke Member

  operation::group-challenges/poke-create[snippets='http-request,request-headers,path-parameters,http-response']
