= Detoxmate API Docs
:toc: left
:toclevels: 2

== Auth API

=== Kakao Social Login

operation::auth/social/kakao[snippets='http-request,request-fields,http-response,response-fields']
operation::auth/social/kakao-invalid-request[snippets='http-request,request-fields,http-response,response-fields']

=== Refresh Access Token

operation::auth/refresh[snippets='http-request,request-fields,http-response,response-fields']
operation::auth/refresh-invalid-request[snippets='http-request,request-fields,http-response,response-fields']

=== Logout

operation::auth/logout[snippets='http-request,request-fields,http-response']
operation::auth/logout-invalid-request[snippets='http-request,request-fields,http-response,response-fields']

== User API

=== Get My Profile

operation::users/me-get[snippets='http-request,request-headers,http-response,response-fields']
operation::users/me-get-unauthorized[snippets='http-request,request-headers,http-response,response-fields']

=== Withdraw My Account

operation::users/me-delete[snippets='http-request,request-headers,http-response']
operation::users/me-delete-unauthorized[snippets='http-request,request-headers,http-response,response-fields']
