package com.detoxmate.notification.domain;

public enum NotificationTypeCode {
    GROUP_JOINED,
    CERTIFICATION_START_TOMORROW,
    GOAL_SETTING_REMINDER,

    CERTIFICATION_CREATED,
    COMMENT_CREATED,
    REACTION_CREATED,

    POKE_RECEIVED,
    POKE_GOAL_SETTING_REMINDER,
    STREAK_WARNING,
    DAILY_CERTIFICATION_REMINDER,
    WEEKLY_GOAL_SUMMARY,
    APP_UNLOCK_REQUESTED,
    FRIEND_UNLOCKED,
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_APP_UNLOCKED,
    FRIEND_TIME_LIMIT_CHANGED,
    APP_RELOCK_REMINDER
}
