package com.detoxmate.notification.domain;

public enum NotificationTypeCode {
    GROUP_JOINED,
    CERTIFICATION_START_TOMORROW,
    GOAL_SETTING_REMINDER,

    CERTIFICATION_CREATED,
    COMMENT_CREATED,
    REACTION_CREATED,

    POKE_RECEIVED,
    POKE_GOAL_SETTING_REMINDER,
    STREAK_WARNING,
    DAILY_CERTIFICATION_REMINDER,
    WEEKLY_GOAL_SUMMARY
}
